GET http://127.0.0.1:5000/api/quizzes/1/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1MzkxMjE3OSwianRpIjoiN2FmMmRhMTgtNGIwNy00YjAwLWFmNWQtNzMyYTE2MTBiNjMxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjE3ZWM0ZTcxLWZkZWEtNGIzOC04ZjE5LThiYzA5MmRiYzgyNiIsIm5iZiI6MTc1MzkxMjE3OSwiY3NyZiI6ImNhYzBlOTc5LTE4ZWEtNGJkOC1iNWMwLTZmMzlmNTY1NjM5ZSIsImV4cCI6MTc1MzkxNTc3OSwicm9sZXMiOlsidXNlciJdLCJ1c2VybmFtZSI6InVzZXIwMDAifQ.VysMSHe-ibPqQ5iuyRVP7oaHd3Y7SwwN7zFOb7JlOUA
Accept: application/json